[package]
name = "ckjm_analyzer"
version = "0.1.0"
edition = "2018"

[dependencies]
fs_extra = "1.2.0"
execute = "0.2.8"
clap = "~2.33"
array_tool = "1.0.3"
walkdir = "2.3.2"
minidom = "*"
itertools = "0.10.1"